/* Text to put at the beginning of the generated file. Probably a license. */

#ifndef mozilla_wr_bindings_h
#define mozilla_wr_bindings_h

#pragma once

/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdio.h>
#include <string.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdlib.h>
#include "context.h"

#define APP_BASE_ADDRESS 2151677952

#define APP_SIZE_LIMIT 131072

#define KERNEL_STACK_SIZE (4096 * 2)

#define MAX_APP_NUM 16

#define USER_STACK_SIZE (4096 * 2)
struct app_manage {
	uint64_t num;
	uint64_t cur;
	uint64_t ads[MAX_APP_NUM + 1];
	
};
struct kel_stack{
	uint8_t data[KERNEL_STACK_SIZE];
};
struct usr_stack{
	uint8_t data[USER_STACK_SIZE];
};
uint64_t get_usr_sp(struct usr_stack *uss);
uint64_t get_kel_sp(struct kel_stack *kes);
extern struct app_manage app_manager;
extern struct usr_stack user_stack;
extern struct kel_stack kernel_stack;
extern struct trap_cont trap_context;

void init_batch();
void  run_next_app();
#endif /* mozilla_wr_bindings_h */

/* Text to put at the end of the generated file */
